set(EDWGentianeMC_RESOURCES
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/README.rst
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/world.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/detector.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/old_source.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/source.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/mapping/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/plugins/materials.conf
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/plugins/material_aliases.def
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/plugins/mappings.conf
)
