set(EDWGentianeMC_RESOURCES
${PROJECT_SOURCE_DIR}/resources/README.rst
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/README.rst
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/world.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/external_cover_polycone.data
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/external_cover.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/brass_rod.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/internal_chamber.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/contact_plate.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/teflon_block.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/internal_crystal_stack.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/top_copper_finger.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/detector_alu_base.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/crystal_support.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/crystal_support_polycone.data
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/detector_envelope.data
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/detector_envelope.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/germanium_crystal.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Detector/crystal_support_base.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/gentiane_assembly.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Sample/sample_box.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Sample/sample.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Shielding/copper_shield_box.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Shielding/internal_lead_shield.geom
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/models/Shielding/core_internal_detector_room.data
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/mapping/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/plugins/materials.conf
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/plugins/materials.def
${PROJECT_SOURCE_DIR}/resources/config/gentiane/geometry/0.1/plugins/material_aliases.def
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/README.rst
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/geant4_control/0.1/README.rst
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/geant4_control/0.1/hits/step_hit_processors.conf
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/geant4_control/0.1/visu/geant4_visualization.mac
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/geant4_control/0.1/physics/em.conf
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/geant4_control/0.1/physics/particles.conf
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/geant4_control/0.1/images/gentiane_g4_sim-test1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/geant4_control/0.1/images/gentiane_g4_sim-test2.jpeg
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/geant4_control/0.1/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/vertexes/0.1/README.rst
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/vertexes/0.1/generators/Detector/detector_generators.def
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/vertexes/0.1/generators/Environment/lab_generators.def
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/vertexes/0.1/generators/Sample/sample_generators.def
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/vertexes/0.1/generators/Shielding/internal_lead_generators.def
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/vertexes/0.1/generators/Shielding/external_copper_generators.def
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/vertexes/0.1/generators/basic_generators.def
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/vertexes/0.1/images/gentiane-floor_cloud_surface_vertexes.jpeg
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/vertexes/0.1/images/gentiane-ceiling_surface_vertexes.jpeg
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/vertexes/0.1/images/gentiane-top_copper_plate_vertexes.jpeg
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/vertexes/0.1/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/primary_events/0.1/README.rst
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/primary_events/0.1/generators/generators.def
${PROJECT_SOURCE_DIR}/resources/config/gentiane/simulation/primary_events/0.1/manager.conf
)
