set(EDWGentianeMC_VERSION_MAJOR 0)
set(EDWGentianeMC_VERSION_MINOR 1)
set(EDWGentianeMC_VERSION_PATCH 0)
set(EDWGentianeMC_VERSION
  "${EDWGentianeMC_VERSION_MAJOR}.${EDWGentianeMC_VERSION_MINOR}.${EDWGentianeMC_VERSION_PATCH}")
